# Generated by Django 2.0.3 on 2019-07-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='menusection',
            old_name='section',
            new_name='name',
        ),
    ]
